name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check backend fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check backend
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

      - name: Check backend clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings

      - name: Test backend
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Build backend
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint
      - name: Unit tests
        run: yarn run test:ci
      - name: Build frontend
        run: yarn run build

      - name: Check for E2E
        id: check-for-e2e
        run: |
          if [ -d "cypress" ]
          then
            echo "has-e2e=true" >> $GITHUB_OUTPUT
          fi

      - name: Start grafana docker
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        run: docker-compose up -d

      - name: Run e2e tests
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        run: yarn run e2e

      - name: Stop grafana docker
        if: steps.check-for-e2e.outputs.has-e2e == 'true'
        run: docker-compose down

      - name: Archive E2E output
        uses: actions/upload-artifact@v3
        if: steps.check-for-e2e.outputs.has-e2e == 'true' && steps.run-e2e-tests.outcome != 'success'
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
